### ISSUE TITLE
Can't get 

### ISSUE THREAD

**Issue by kootenpv** [DEAP/deap#110]
Tried to `pickle.load` an object containing a deap object and I'm getting the following error:

    AttributeError: Can't get attribute 'FitnessMax' on <module 'deap.creator' from '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/deap/creator.py'>

Any idea what could be the problem? I actually don't care so much about the evolution object as much as only the best model.

**Comment by cmd-ntrf** [comment]
Fitness classes in DEAP are created dynamically. In order to unpickle the objects, the objects must have been defined previously in the same way they were defined before the evolution (`creator.create("FitnessMax",...)`).

Easiest solution to this problem, import the module in which you have called `creator.create` in the program that tries to unpickle the object.

This should no longer be a problem in DEAP 2.0 as explained in Pull-request #76 
https://github.com/DEAP/deap/pull/76.
