### ISSUE TITLE
The duplicated individual from crossover and mutation in algorithms.eaSimple are always evaluated

### ISSUE THREAD

**Issue by weixuanfu2016** [DEAP/deap#162]
The `varAnd` function used by algorithms.eaSimple can reset the fitness values of individuals from crossover or mutation no mather whether inividuals are novel in GP. For example, if the parent are the same, `tools.cxTwoPoint` may generate "twins" which are exactly same as their "parents". Then, evaluating the duplicated individuals should waste computational time. It is related to [a issue](https://github.com/rhiever/tpot/issues/303) in TPOT(https://github.com/rhiever/tpot). Maybe adding some checkings in the `algorithms.eaSimple ` and make sure that crossover and mutation generate new individuals. Below is a demo for adding this function into `varAnd`

```
def varAnd(population, toolbox, cxpb, mutpb):
    offspring = [toolbox.clone(ind) for ind in population]

    # Apply crossover and mutation on the offspring
    for i in range(1, len(offspring), 2):
        if random.random() < cxpb:
            ind1, ind2 = str(offspring[i - 1]), str(offspring[i])
            offspring[i - 1], offspring[i] = toolbox.mate(offspring[i - 1], offspring[i])
            for child in [offspring[i - 1], offspring[i]]:
                # check if child is the same as their parents
                if str(child) != ind1 and str(child) != ind2:
                    del child.fitness.values

    for i in range(len(offspring)):
        if random.random() < mutpb:
            tmpind = str(offspring[i])
            offspring[i], = toolbox.mutate(offspring[i])
            if tmpind != str(offspring[i]):
                del offspring[i].fitness.values

    return offspring
```
@rhiever

**Comment by fmder** [comment]
This would require every type of individual to have a __str__ method. I would strongly encourage you to define your own algorithm that makes this check. I don't think it is necessary in the general case where most individuals are modified during variation.

**Comment by rhiever** [comment]
I would like for this issue to be reopened and considered a bug.

My reasoning for that is that we are using the DEAP mutation and crossover functions. There are several cases where the DEAP mutation and crossover functions don't always generate modified individuals:

1) Mutation replaces a value with the same value
2) Mutation replaces a subtree with the same subtree
3) Crossover between two individuals that are clones
etc...

I think there should be checks in DEAP that the new individual(s) generated by mutation and crossover are actually new individuals. It seems those checks don't currently exist.

**Comment by fmder** [comment]
We provide the most basic, simple and general algorithms as possible in the
algorithms module so that users can copy paste and enhance them to do what
they want. Accomplishing similarity checking is none trivial for most data
types. It would require either a general operator that can establish
similarity between any two individual or require every data type to
implement this similarity check. None of these seems reasonable to me. This
is why I won't reopen the issue.

The simplest solution to this problem is to copy the varAnd operator and
accomplish the modification in the copied version. A second solution would
use a memoize
<https://docs.python.org/3/library/functools.html#functools.lru_cache>
around the evaluation function so that twins are not evaluated twice. A
third solution would use the varOr variator which does not delete the
fitness of copied individuals.

Best regards,

2016-11-28 16:17 GMT-05:00 Randy Olson <notifications@github.com>:

**Comment by geekan** [comment]
Very common issue and I use lru_cache finally because it's dead simple
