### ISSUE TITLE
Fitness vs Evaluate

### ISSUE THREAD

**Issue by ido4848** [DEAP/deap#178]
Hello, i'm newbie to DEAP.
I wonder what's the meaning of an individual's fitness, as seen here in the one max example:

**`creator.create("FitnessMax", base.Fitness, weights=(1.0,)`**
`creator.create("Individual", list, fitness=creator.FitnessMax)`

versus

`def evaluate(individual):`
`    return sum(individual),`
**`toolbox.register("evaluate", evaluate)`**

because i see that the usage is as following:

`fitnesses = list(map(toolbox.evaluate, pop))`

so fitness is the value of evaluate?
then, what's the role of fitness? when is it used? (i'm referring to the FitnessMax sutff)

This is an issue because i think it is not fully explained in the docs.
Thank's.

**Comment by fmder** [comment]
The `FitnessMax` is an attribute attached to an individual meaning its goodness. It also indicates whether the problem is minimization or maximization.

The `fitnesses` are the fitness values for each individual as given by the evaluation function. Since we didn't wanted the user to worry about implentation details, and certainly not wanted him to modify the individuals during evaluation, the simplest evaluation function returns a fitness the we attach later to an `individual.fitness.value`.

DEAP's documentation is not meant as an introduction to evolutionary algorithms. As an introduction we refer to these two excellent books:

- M. Mitchell. An Introduction to Genetic Algorithms. MIT Press, 1998.
- "Riccardo Poli and William B. Langdon and Nicholas Freitag McPhee". A FIELD GUIDE TO GENETIC PROGRAMMING.
