### ISSUE TITLE
what content should be contained in the "my_guess.json" file?

### ISSUE THREAD

**Issue by fhyme** [DEAP/deap#202]
I want to initialize a population wit my own defined content. And I find an example [Seeding a Population](http://deap.readthedocs.io/en/master/tutorials/basic/part1.html?highlight=json) in the tutorials. 

But what content is contained in the "my_guess.json" file? And is there any typical example of this file?

**Comment by fmder** [comment]
This tutorial is probably the worstly explained. Its intend was to put out
the possibility rather than showing the best way to do it, because it
depends on the type on individual you have.

The my_guess.json content strongly depends on how you code your
initialization functions. For the tutorial, since the population and
individuals are lists, it would be as follow :

[
    [1,2,3,4],
    [2,3,4,5]
]

**Comment by fhyme** [comment]
@fmder Thanks for your help. I find another way to initialize a population I want to use. 
As you said, The my_guess.json content strongly depends on the code of my initialization functions.

**Comment by LouiValley** [comment]
> @fmder Thanks for your help. I find another way to initialize a population I want to use.
> As you said, The my_guess.json content strongly depends on the code of my initialization functions.

Hi fhyme, I have the same question with you. Could you please tell me what is your "another way to initialize a population" ?
