### ISSUE TITLE
How to select individuals in paretofront by hypervolume

### ISSUE THREAD

**Issue by SvennoNito** [DEAP/deap#261]
Hey,

after some struggle I've managed to import the hypervolume methode `from deap.benchmarks.tools import hypervolume`. I know that I can use the hypervolume as a measure on how diverse my indivualds are - and also to kick out indivuals that do not contribute to the hypervolume.

If I use the method, however, I get a floating point number, probably refering to the total hypervolume of my paretofront. I saw that there is the [ tools.indicator](https://github.com/DEAP/deap/blob/master/deap/tools/indicator.py) function that seems to do what I want. I don't see it [here](http://deap.readthedocs.io/en/master/api/tools.html) though, neither can I call it by using `tools.indicator(paretofront)`. I import it by using `from deap import tools`. If I type tools.[tab] then I see the indicator method, but I get this error: `TypeError: 'module' object is not callable`. 

Do I do something wrong?

![image](https://user-images.githubusercontent.com/32299254/36283395-b4410f82-12a4-11e8-88b0-35dd8b705375.png)

**Comment by SvennoNito** [comment]
Never mind, `tools.indicator.hypervolume(paretofront)` did the job. Yet another question: it only returns the individual with the smallest contribution to the hypervolume right? So I can eliminate this individual and have to repeat this procedure for arbitrary amount of times? Or how would be the logic in DEAP?

**Comment by fmder** [comment]
Exactly you remove one individual at a time this is what makes the
technique so computationally expensive.

**Comment by SvennoNito** [comment]
Thanks fmder. Are there any powerful alternatives in DEAP? Rakes for example? Or would you recommend using hypervolume nevertheless?

![image](https://user-images.githubusercontent.com/32299254/36285765-35b8815a-12ad-11e8-985c-b7bcb54a8f66.png)

**Comment by fmder** [comment]
I'm not aware of rakes. For a relatively small population for what i know
(I've been out of the evolutionary computation world for a few years now)
hypervolume is the best technique.

**Comment by SvennoNito** [comment]
All righty, thanks for the quick answer. Last question: would you kick out solutions until a certain number of individuals is reached, until a minimum hypervolume or until the rate of loss in hypervolume reaches a certain threshold? Are there any criteria I can relate to? Or any numbers (e.g. xx indiviuals cover a good spread, a hypervolume of xx is a good indicator or something)?

**Comment by fmder** [comment]
The "usual" way is to do it is to keep a constant number of individuals
after each generation because depending if you are at the begin or at the
end of the optimization, the hypervolume may vary a lot and render the
other techniques hard to parametrize.

Le 15 févr. 2018 18:26, "SvennoNito" <notifications@github.com> a écrit :

All righty, thanks for the quick answer. Last question: would you kick out
solutions until a certain number of individuals is reached, until a minimum
hypervolume or until the rate of loss in hypervolume reaches a certain
threshold? Are there any criteria I can relate to? Or any numbers (e.g. xx
indiviuals cover a good spread, a hypervolume of xx is a good indicator or
something)?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/DEAP/deap/issues/261#issuecomment-366096612>, or mute
the thread
