### ISSUE TITLE
modify gp.addEphemeralConstant signature for consistency?

### ISSUE THREAD

**Issue by tyarkoni** [DEAP/deap#52]
Very minor suggestion, but in the current version of the gp module, there appear to be minor inconsistencies in the API for addEphemeralConstant vs. addTerminal or addPrimitive:

```python
def addEphemeralConstant(self, name, ephemeral, ret_type):

# versus...
def addPrimitive(self, primitive, in_types, ret_type, name=None):
def addTerminal(self, terminal, ret_type, name=None):
```

I don't know if there's a principled reason for this, but if not, it might be helpful to keep the arguments in the same order across the API. Would be happy to submit a PR.

**Comment by cmd-ntrf** [comment]
Wow, this took me time to answer... I am deeply sorry!

The reason why is that the name is required for Ephemeral as it defines them while name for Primitive and Terminal is more a convenient feature than a necessity, which is why it is None by default.

It would be more consistent to have the argument at the same position, but I still prefer to have the name in first position for the Ephemeral for some reason that I am not able to word right now.
