### ISSUE TITLE
Knapsack example: Why multi objective?

### ISSUE THREAD

**Issue by fxg36** [DEAP/deap#571]
Isn't it traditionally the case that only the value needs to be optimized? In the case of the example, the algorithm only looks for the best value-to-weight ratio.

**Comment by fmder** [comment]
You are right that the knapsack problem requires to find a solution that is under a given threshold. This example does not differ in the knapsack definition but only on how it is approached. Instead of tackling the threshold as a constraint it is tackled as an objective. This often (IMHO) a good representation of constraints with evolutionary algorithms.
