### ISSUE TITLE
Minimum acceptable population size

### ISSUE THREAD

**Issue by quant12345** [DEAP/deap#585]
How can I calculate an acceptable minimum number of generations and population based on the size of the chromosome?
Need to know this, because there is a lot of data, and it will require a lot of resources.

**Comment by jameshughes89** [comment]
This does not sound like an issue with DEAP, but a question about evolutionary computation in general.

**Comment by fmder** [comment]
I don't think there is much theoretical ground on this. I know the CMA-ES literature suggests 20x chromosome size for the population size for harder problems. This can give you a good idea where to start. As for number of generation, I guess this should more be based on your fitness and population convergence rather than a fixed number.
