### ISSUE TITLE
History graph not working.

### ISSUE THREAD

**Issue by TOP1RM** [DEAP/deap#649]
Hello,

I am Rémi MOCHON, a DEAP user. Here is my issue:

I intend to use the class `History` to plot the genealogy of the evolution, along with recording every individual whose fitness has been evaluated.

When I follow the steps in DEAP's documentation (https://deap.readthedocs.io/en/master/api/tools.html#history), I end up with a disordered graph, without numbers on the nodes (see png file attached). I am studying the code so I begin to understand how `History` works, but I am not sure it is adapted for my script (see py file attached). I am using genetic programming (`gp` module) and the `eaSimple` evolution algorithm (the later uses `VarAnd` to vary the pool of selected individuals).

Could someone provide me some working example using `History` in Genetic Programming (thus using the `gp` module), so I can produce a nice graph like in the documentation of DEAP ?
![Graph](https://user-images.githubusercontent.com/82977638/174130501-4fb2ccbd-3db6-4659-8867-f603d20f9e7d.png)

Looking forward for your answer.

Best regards,
Rémi MOCHON

[script_and_png.zip](https://github.com/DEAP/deap/files/8921270/script_and_png.zip)

**Comment by Yasu31** [comment]
I know I'm answering a half-year-old issue, but since I had the same question I'll post my solution for the future;
at the end of your code (or the example code from https://deap.readthedocs.io/en/master/overview.html ), just draw the graph using pygraphviz (you may have to do `sudo apt-get install graphviz graphviz-dev` and then `pip install pygraphviz`) with the folliowing code (the formatting is optional, of course)

```python
import pygraphviz as pgv

graph = pgv.AGraph(history.genealogy_tree, directed=True)
graph = graph.reverse()     # Make the grah top-down
# set attribute for each element to make it look nice
# attributes: https://graphviz.org/doc/info/attrs.html
for n in graph.nodes():
	n.attr["shape"] = "hexagon"
	n.attr["color"] = "violet"
	n.attr["fillcolor"] = "violet"
	n.attr["style"] = "bold,filled"

graph.graph_attr["bgcolor"] = "black"
graph.graph_attr["splines"] = "curved"
graph.edge_attr["color"] = "green"
graph.edge_attr["arrowhead"] = "open"

graph.layout(prog="dot")    # layout with dot
graph.draw("family_tree.png") # draw png
```
which will create a nice looking graph, probably what the commenter was looking for.

![family_tree](https://user-images.githubusercontent.com/16713520/210540403-3bea9d6e-f78a-4bfc-a18e-238ba6ed3ccf.png)
