### ISSUE TITLE
Example - bad code lines

### ISSUE THREAD

**Issue by torresweb** [DEAP/deap#99]
Hello,

I am trying to understand this example:
http://deap.readthedocs.org/en/master/examples/ga_onemax.html

but I think the code lines are in wrong position and not match the explanation text. Please, could you check it?

**Comment by fmder** [comment]
You are right, I just recently discovered Sphinx `start-after` and `end-before` attributes that will end this once and for all!

Thanks for reporting

**Comment by valencik** [comment]
Any chance of a fix?
Or will you accept a PR that fixes the line number refs in [deap/doc/examples/ga_onemax.rst](https://github.com/DEAP/deap/blob/master/doc/examples/ga_onemax.rst)?

**Comment by fmder** [comment]
Devs are pretty busy at the time, if you can propose a PR that includes
Sphinx ability to start code at a given comment it would be great!

2015-11-16 17:16 GMT-08:00 Andrew Valencik <notifications@github.com>:

**Comment by Ogaday** [comment]
As a stopgap measure, I submitted a pull request ( #119 ) that reverts the commit that adds the commentary to `onemax.py`. I also submitted an alternative pull request (# 120 ) in which I manually fixed the line numbers, so one can be submitted, the other rejected. Neither are permanent solutions, perhaps, but I think it would be good to fix the documentation.

I'm in favour of reverting the commit that added the comments, because they seem a little verbose when Python is already very expressive and there are docs accompanying the code.
